---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.thesis.local
  resources:
  - microservicemessagingprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.thesis.local
  resources:
  - microservicemessagingprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - messaging.thesis.local
  resources:
  - microservicemessagingprofiles/status
  verbs:
  - get
  - patch
  - update
